### ISSUE TITLE
custom axes can not mine quark cave roots at all

### ISSUE THREAD

**Issue by GiantLuigi4** [GiantLuigi4/dynamic-weapons#3]

**Comment by SonicJDF** [comment]
kinda cringe

**Comment by GiantLuigi4** [comment]
:suspiciouseyes:

**Comment by SonicJDF** [comment]
hopefully it can be fixed, can't wait it's very important and critical to the mods success.

**Comment by GiantLuigi4** [comment]
~~I made it worse btw~~

**Comment by GiantLuigi4** [comment]
Wound up expanding it to being that tools can’t mine anything unless it’s the porper tool for that block

**Comment by SonicJDF** [comment]
oh no, this is so sad.
