### ISSUE TITLE
Missing Required Mods Screen Crash

### ISSUE THREAD

**Issue by WenXin20** [GiantLuigi4/dynamic-weapons#6]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Dynamic Weaponry Beta v2`

My game crashed when it tried to load this mod instead of displaying that it was missing the required mod Assorted Utils, which I wasn't aware of.
[Crash Report](https://gist.github.com/WenXin20/5a28e6fc3e5d2d940be2b9dbebeb5227)

**Comment by GiantLuigi4** [comment]
It is marked as a dependency in the mods.toml, so idk why it doesn’t say it requires assorted utils (will ask in MMD later), but it is marked as a dependency on the curseforge page.

**Comment by GiantLuigi4** [comment]
I may have just fixed this, but I’m not on pc to test rn.

**Comment by WenXin20** [comment]
Alright, no problem

**Comment by GiantLuigi4** [comment]
So, the fix I thought would work while on mobile did not, however I have now actually fixed it
